LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := QPGallery
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := QPGallery.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := Gallery Gallery2 Gallery3D Photos 
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)
